added python installer, logging to syslog, etc.

diff --git a/scripts/startx b/scripts/startx
--- a/scripts/startx
+++ b/scripts/startx
@@ -49,6 +49,30 @@ cd "$basedir"
 
 inifile="$basedir/palma.ini"
 
+if ! test -r "$inifile"; then
+    inifile=/etc/palma.ini
+    basedir=/usr/share/palma
+fi
+
+if ! test -r "$inifile"; then
+    echo "Could not open $inifile, exiting"
+    exit 1
+fi
+
+dbfile=palma.db
+if test -d /var/lib/palma; then
+    dbfile=/var/lib/palma/palma.db
+fi
+
+wwwroot=/var/www/html
+if test -d /usr/share/palma; then
+    wwwroot=/usr/share/palma
+fi
+
+rundir=/var/run/palma
+mkdir -p $rundir
+chown $user $rundir
+
 # Get some configuration parameters from ini file.
 export DISPLAY
 DISPLAY=$(grep "^id[ ]*=" "$inifile"|perl -pe 's/^[^=]*=[ ]*["]?([^"]*)["]?/\1/')
@@ -99,7 +123,7 @@ runx "/usr/bin/xset s off"
 # Wait a littĺe before the screensaver image hides the background.
 /bin/sleep 5
 
-rm palma.db
+rm -f "$dbfile"
 
 # Create directory for application settings if needed.
 mkdir -p "$userhome/.config"
@@ -114,10 +138,16 @@ if test -f /usr/bin/dwb; then
     cp -a settings/dwb "$userhome/.config"
 elif test -f /usr/bin/midori; then
     webbrowser=midori
+else
+    echo "Could not find any supported web browser!"
 fi
 
 # Fix ownership of directory for application settings.
 chown -R "$user:$user" "$userhome/.config"
+
+# Create cache directory for openbox
+mkdir -p "$userhome/.cache"
+chown -R "$user:$user" "$userhome/.cache"
 
 # 0=initial state
 # 1=screen saver running
@@ -129,8 +159,8 @@ set +x
 
 while true; do
 
-    if test -f palma.db; then
-        usercount=$(sqlite3 palma.db "select count(*) from user")
+    if test -f "$dbfile"; then
+        usercount=$(sqlite3 "$dbfile" "select count(*) from user")
     else
         usercount=0
     fi
@@ -142,7 +172,7 @@ while true; do
         # Kill the VNC viewer if it was running.
         date +"%F %T start $webbrowser with screensaver"
         killall -q ssvncviewer
-        runx "/usr/bin/php control.php doLogout=ALL"
+        runx "/usr/bin/php $wwwroot/control.php doLogout=ALL"
         case $webbrowser in
             dwb)
                 # Start DWB in presentation mode.
@@ -172,8 +202,8 @@ while true; do
             # Start the VNC viewer process, so usercount can share their desktop.
             date +"%F %T kill $webbrowser"
             killall --user $user --quiet $webbrowser
-            runx "/usr/bin/php SSVNCDaemon.php" &
-            runx "/usr/bin/touch last_activity"
+            runx "/usr/bin/php $wwwroot/SSVNCDaemon.php" &
+            runx "/usr/bin/touch $rundir/last_activity"
             state="2"
         fi
     elif test "$state" = "2"; then
@@ -184,7 +214,7 @@ while true; do
             state="0"
             continue
         else
-            ACTIVITY=$(date -r last_activity '+%s')
+            ACTIVITY=$(date -r $rundir/last_activity '+%s')
             NOW=$(date '+%s')
             DIFF=$((NOW - ACTIVITY))
             if test $((DIFF / 60)) -ge "$TIMEOUT"; then
